theme: jekyll-theme-tactile

baseurl: 'https://ibrahimhuycn.github.io/StaffEvaluation'

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  internal: true
  url: ./index.md
- text: Add a new page
  internal: true
  url: ./aasandha-workflow.md
- text: Aasandha Workflow
  internal: true